CREATE DATABASE EXO_BANKING_DB;

CREATE TABLE CLIENT (
    clientId INT NOT NULL PRIMARY,
    fullName VARCHAR(50) NOT NULL,
    dateOfBirth VARCHAR(30),
    address VARCHAR(20),
    accounts VARCHAR(20)
);

CREATE TABLE AGENT (
    agentId INT NOT NULL PRIMARY,
    fullName VARCHAR(50) NOT NULL,
    dateOfBirth VARCHAR(30),
    address VARCHAR(20),
    clientId INT NOT NULL
);

CREATE TABLE ACCOUNT (
    clientId INT NOT NULL,
    account VARCHAR(20) NOT NULL
);

CREATE TABLE BANK (
    bankId INT NOT NULL PRIMARY,
    bankName VARCHAR(20)
)