CREATE DATABASE EXO_BANKING;

CREATE TABLE CLIENT (
    clientId INT NOT NULL CONSTRAINT PRIMARY KEY,
    fullName VARCHAR(50) NOT NULL,
    dateOfBirth VARCHAR(30),
    adress VARCHAR(20),
    accounts VARCHAR(20)
);

CREATE TABLE AGENT (
    agentId INT NOT NULL CONSTRAINT PRIMARY KEY,
    fullName VARCHAR(50) NOT NULL,
    dateOfBirth VARCHAR(30),
    adress VARCHAR(20),
    clientId INT NOT NULL
);

CREATE TABLE ACCOUNT (
    clientId INT NOT NULL CONSTRAINT PRIMARY KEY,
    account VARCHAR(20) NOT NULL
);

CREATE TABLE BANK (
    bankId INT NOT NULL CONSTRAINT PRIMARY KEY,
    bankName VARCHAR(20)
)